const express = require('express');
const path = require('path');
const port = process.env.PORT || 3020;
const app = express();
const multer = require('multer');
const fs = require('fs');
const { spawn } = require('child_process');


app.set('port', port)
const upload = multer({ dest: 'temporary/' });

app.post('/remove', upload.single('image'), (req, res) => {
    const input_path = req.file.path;
    // file.filename = auto generated by multer
    const output_path = `processed/${req.file.filename}.png`;

    const python = spawn('python3', ['python/remove_bg.py', input_path, output_path]);

    python.on('close', (code) => {
        if (code === 0) {
          res.sendFile(path.resolve(outputPath), () => {
            fs.unlinkSync(inputPath);    
            fs.unlinkSync(outputPath);  
          });
        } else {
          res.status(500).send('failed to remove the background');
        }
      });


})



app.listen(app.settings.port, () => {
    console.log('App working on ', app.settings.port);
});